### ISSUE TITLE
Cannot leave vdi-stream-client

### ISSUE THREAD

**Issue by bigla** [mbroemme/vdi-stream-client#1]
Hi,

I just installed from AUR and made it work - so far documentation was helpful!

Now, I am not able to "leave the window" with my keyboard / mouse cursor inputs using ctrl+alt (which was a pretty useful info printed in the title bar).

Situation is funny now, because every time I try to kick myself from parsec, I get reconnected, so no chance to leave the streaming window on the client side.

On the host side, I cannot quit parsec, because I cannot kick myself (long enough for my screen to go back from black).

I feel a bit stuck :D

Workaround?
ctrl+alt+F1 (/F2/F3 etc.) seem to work, so i might switch to console and kill the streaming client from there.

**Comment by mbroemme** [comment]
@bigla Could you tell me which window manager you are using and if ctrl + alt was configured for some shortcut in your window manager?

And if you pressed ctrl+alt, does the hint in the title bar is being removed? If so you should be able to move the mouse cursor again outside of the window.

**Comment by bigla** [comment]
> @bigla Could you tell me which window manager you are using

I am using xfce4 so WM is xfwm4 version 4.16.1-1.
As for any active shortcuts - to be honest - I don't recall ever setting a shortcut to ctrl + alt.

> And if you pressed ctrl+alt, does the hint in the title bar is being removed?

Yes, the hint is removed. After pressing again it is visible again. I was not able to move my mouse out of the window in any situation.

I don't know if it is usual or not, but if you want I can offer you some screen sharing call or similar demonstrating the situation.

**Comment by mbroemme** [comment]
> Yes, the hint is removed. After pressing again it is visible again. I was not able to move my mouse out of the window in any situation.

Could you also tell me which Windows application was running during this situation? I have an idea that it might be related to relative mouse grab.

**Comment by mbroemme** [comment]
@bigla Should be fixed with PR #4, if not please report back.
