### ISSUE TITLE
Parsec 6.0 breaks the build

### ISSUE THREAD

**Issue by Nexxkinn** [mbroemme/vdi-stream-client#5]
compiling the repo with the latest parsec version cause a compile error:
```bash
make  all-recursive
make[1]: Entering directory '/workspace/template-nix/vdi-stream-client-0.2.0'
Making all in src
make[2]: Entering directory '/workspace/template-nix/vdi-stream-client-0.2.0/src'
gcc -DHAVE_CONFIG_H -I. -I..    -I/usr/include/libusb-1.0 -I/usr/include/libusb-1.0    -D_REENTRANT -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/SDL2 -g -O2 -c -o vdi_stream_client-parsec.o `test -f 'parsec.c' || echo './'`parsec.c
parsec.c: In function ‘vdi_stream_client__cursor’:
parsec.c:76:14: error: ‘ParsecCursor’ {aka ‘struct ParsecCursor’} has no member named ‘modeUpdate’; did you mean ‘imageUpdate’?
   76 |  if (cursor->modeUpdate == SDL_TRUE) {
      |              ^~~~~~~~~~
      |              imageUpdate
make[2]: *** [Makefile:429: vdi_stream_client-parsec.o] Error 1
make[2]: Leaving directory '/workspace/template-nix/vdi-stream-client-0.2.0/src'
make[1]: *** [Makefile:385: all-recursive] Error 1
make[1]: Leaving directory '/workspace/template-nix/vdi-stream-client-0.2.0'
make: *** [Makefile:326: all] Error 2
```

looking at their SDK changes with [previous version ( 5.0 )](https://github.com/parsec-cloud/parsec-sdk/compare/5.0...6.0#diff-6bdd288efb95c09792c5785e885b9f33b36933430d5010d9643bd2f75d870e21R679), they replace `modeUpdate` with `hidden`. changing the code will compile it fine.

**Comment by mbroemme** [comment]
Thanks @Nexxkinn, I will fix it with one of the next PRs (have fixed it already locally) but need to test the different grab methods of the client applications a bit more.

**Comment by Nexxkinn** [comment]
I see, thanks for the update.
Mind if I post my own solution into the merge request?

**Comment by mbroemme** [comment]
@Nexxkinn I have overseen the comment, actually next time you can just create the PR and I will review it.
